; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Mon Apr 16 2018 20:44:39 GMT+0200 (CEST)
G91               ; relative positioning
G1 Z5 F7200 S2    ; lift Z relative to current position
G1 S1 Y-389 F3600 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y5 F7200       ; go back a few mm
G1 S1 Y-389 F360  ; move slowly to Y axis endstop once more (second pass)
G1 Z-5 F7200 S2   ; lower Z again
G90               ; absolute positioning