; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Mon Apr 16 2018 20:44:39 GMT+0200 (CEST)
G91               ; relative positioning
G1 Z5 F600 S2    ; lift Z relative to current position
G1 S1 X-297 F7200 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F7200       ; go back a few mm
G1 S1 X-297 F360  ; move slowly to X axis endstop once more (second pass)
G1 Z-5 F7200 S2   ; lower Z again
G90               ; absolute positioning